repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: coverage
        name: Generate coverage report
        entry: poetry run coverage run -m pytest
        language: system
        pass_filenames: false
        require_serial: true
  - repo: local
    hooks:
      - id: generate-coverage-report
        name: Generate HTML coverage report
        entry: poetry run coverage html -d .coverage_html
        always_run: true
        language: system
        pass_filenames: false
        require_serial: true
